server:
  port: 9002

spring:
  application:
  name: lagou-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: service-code-router # 我们自定义的路由 ID，保持唯一
#          uri: http://127.0.0.1:8081       # 目标服务地址
          uri: lb://lagou-service-code                                                                    # gateway网关从服务注册中心获取实例信息然后负载后路由
          predicates:                                         # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/code/**
        - id: service-user-router # 我们自定义的路由 ID，保持唯一
#          uri: lb://lagou-service-user                                                                    # gateway网关从服务注册中心获取实例信息然后负载后路由
          uri: http://127.0.0.1:8096       # 目标服务地址
          predicates:                                         # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/user/**
#            - Cookie=123
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: DEFAULT_GROUP
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 127.0.0.1:9999
        port: 8919
      # Sentinel Nacos数据源配置，Nacos中的规则会自动同步到sentinel流控规则中
#      datasource:
#        # 自定义的流控规则数据源名称
#        flow:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            data-id: ${spring.application.name}-flow-rules
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow  # 类型来自RuleType类
#        # 自定义的降级规则数据源名称
#        degrade:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            data-id: ${spring.application.name}-degrade-rules
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: degrade  # 类型来自RuleType类

logging:
  level:
    org.springframework.cloud.gateway: trace
